### ISSUE TITLE
Change behavior for 1.x

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/directory-colorfy#10]
Couples with #8 
colorfy currently adds a style block to an svg:

``` CSS
circle, ellipse, line, path, polygon, polyline, rect, text { fill: ' + color + ' !important; } 
```

It does something similar with stroke when it detects if a stroke is present.

This has worked to a degree but with the ability to embed SVGs coming to Grunticon for 2.0, we need to have a better system. Changing the `fill` and `stroke` attributes, except in the case where they are set to `"none"`, is a better way to go about this.

Unfortunately, it is a Bad Idea™ to use regex on XML/HTML/SVGs - so, we're going to need to use something else to change the attributes - https://github.com/tmpvar/jsdom can allow us to load the svg in a dom-like scenario and then run JS against it. Unfortunately, this makes the process async, so the entirety of the API is going to have to change.
